# AWSTemplateFormatVersion: Specifies the CloudFormation template format version.  
AWSTemplateFormatVersion: "2010-09-09"

# Description: A brief description of the template.  
Description: Create an EC2 instance in a public subnet.

# Parameters: Defines input values that you can specify when creating a stack from this template.    
# InstanceType, KeyName, AMIId are defined here, allowing for customization.    
# Type: 'AWS::EC2::KeyPair::KeyName' and Type: 'AWS::EC2::Image::Id' are specific AWS CloudFormation types for validation.    
Parameters:
  KeyPairName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small

  AmiId:
    Description: AMI ID (e.g., Amazon Linux 2)
    Type: AWS::EC2::Image::Id
    Default: ami-0c02fb55956c7d316  # update for your region

# Resources: Declares the AWS resources to be created.    
# EC2Instance: The logical ID for your EC2 instance.    
# Type: 'AWS::EC2::Instance': Specifies that this resource is an EC2 instance.    
# Properties: Defines the configuration of the EC2 instance, such as ImageId, InstanceType, KeyName, and Tags.    
# !Ref AMIId, !Ref InstanceType, !Ref KeyName: These are intrinsic functions that reference the values provided in the Parameters section.    
# Tags: Key-value pairs for organizing and identifying your resources.    
# SecurityGroupIds: You can specify an existing security group by its ID or define a new one within the template.      
# UserData (commented out): Allows you to provide a script that runs when the instance is launched, useful for initial setup.  
Resources:
  # Security Group
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH from your IP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # change for security
      Tags:
        - Key: Name
          Value: EC2SecurityGroup

  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: MyCFNEC2Instance

# Outputs: Defines values that are returned after the stack is created, such as the InstanceId and PublicIp of the EC2 instance.  
# !Ref EC2Instance: References the logical ID of the EC2 instance to get its ID.    
# !GetAtt EC2Instance.PublicIp: Retrieves a specific attribute (PublicIp) of the EC2 instance.    
Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance

  PublicIp:
    Description: Public IP of the EC2 Instance
    Value: !GetAtt EC2Instance.PublicIp
